### ISSUE TITLE
What versions of Windows does this work on?

### ISSUE THREAD

**Issue by Darthagnon** [MicaForEveryone/MicaForEveryone#124]
I am looking for an alternative to the now defunct [glass8.eu](https://web.archive.org/web/20220625201001/https://glass8.eu/), and am wondering if MicaForEveryone is indeed for everyone. Unfortunately, I couldn't find any information in the Wiki or README about what versions of Windows this will work on. If I recall correctly, mica was introduced in Win10 v1809, but it seems this software does a lot more than just mica? And the only references to Windows versions were offhand, with uncommonly-used version numbers, in the Wiki, and there were different version requirements for different features.

Any chance you could add a list of 
1. What versions of Windows MicaForEveryone should work on
2. What versions of Windows MicaForEveryone is actually tested on

**Comment by Darthagnon** [comment]
For the record, I use Win7, Win8.1 and Win10v1709

**Comment by dongle-the-gadget** [comment]
Currently, Windows 11 is the only version of Windows that this tool officially supports, with most (21H2) or all (22H2+) features available.

All versions of Windows 10 since 2004 lacks Backdrop types, and also has compatibility issues (see #65).

Technically you can push MFE as far as 1903, however this is untested.

**Comment by Darthagnon** [comment]
Thank you! Guess I'll stick with Glass8 for the moment (Win8.1-Win10 v1909)

**Comment by dongle-the-gadget** [comment]
I've added a Wiki FAQ for this. Closing this issue.
