### ISSUE TITLE
Blank display after program start

### ISSUE THREAD

**Issue by pcqxbk** [MicaForEveryone/MicaForEveryone#266]
No matter how I start the program (normal user or admin user), both I get a blank page。
If you can, please open this link below to view：
https://s1.ax1x.com/2023/03/02/ppFaEcR.png

**Comment by threethan** [comment]
Had this as well. Seems to be somehow caused by your config file. Not gonna bother properly figuring it out what specifically leads to this issue, but here's an example of a config that causes it for me.
[MicaForEveryone.conf.txt](https://github.com/MicaForEveryone/MicaForEveryone/files/11163612/MicaForEveryone.conf.txt)
