### ISSUE TITLE
Blue Titlebar

### ISSUE THREAD

**Issue by amymor** [MicaForEveryone/MicaForEveryone#361]
**Describe the bug**
titlebar of explorer and console and other apps revert back to default windows blue color while im using different accent color for title bar.

**To Reproduce**
1. Enable blur behind

**Screenshots**
![Screenshot (108)](https://github.com/MicaForEveryone/MicaForEveryone/assets/54497554/d0e29567-9ca1-44f9-8315-c7c5824e3829)

**Windows Version**
win11 22h2 22621.1928

**Additional context**
without blur behind the app will be useless because all other place look good.

**Comment by dongle-the-gadget** [comment]
Expected behavior from Windows.

**Comment by amymor** [comment]
so there is no way to fix it?

**Comment by dongle-the-gadget** [comment]
No.

**Comment by HerMajestyDrMona** [comment]
Is it really the expected behaviour from Windows?

My default system color is not blue. It's green.

When "Blur behind" is enabled, the entire window (including the title bar) get's a nice glassy effect:

![MicaProblem3](https://github.com/MicaForEveryone/MicaForEveryone/assets/24290461/4f166230-fe60-42fe-9450-c4a08180290c)


However, it's too transparent for normal usage.
In the other case, when just Mica and "Extend frame into..." are selected, the active window title bar gets blue:
![MicaProblem1](https://github.com/MicaForEveryone/MicaForEveryone/assets/24290461/346f6c98-4d5c-41b0-a497-25b46b768b46)



When the window is inactive, the nice mica effect gets also applied to the title bar:

![MicaProblem2](https://github.com/MicaForEveryone/MicaForEveryone/assets/24290461/3d0f7b55-1c93-49c8-8ce4-9fec55823080)


If it's the expected behavior from Windows, why the title bar is blue, and not e.g. black as the selected accent color?
