### ISSUE TITLE
option to control amount of blur on acrylic

### ISSUE THREAD

**Issue by rosnyeng** [MicaForEveryone/MicaForEveryone#70]
Not a fan of Mica bcoz the blur intensity  is not to my liking but the acrylic in this looks more like aero blur. Want something in between..that looks like the Acrylic blur on Macos finder 🙂

**Comment by dongle-the-gadget** [comment]
Unfortunately this is impossible without hooking into DWM, which is not something I'm planning to do (it's just too many risks for little yields). @xmine64 what are your opinions?

**Comment by xmine64** [comment]
Yes I think it's not possible to do it without implementing a hook. I'm not against it despite it can be unstable and breaks on updates of Windows, my only problem is I don't know enough to do it and even I don't know where to start.

**Comment by dongle-the-gadget** [comment]
Marking as won't fix...

**Comment by rounk-ctrl** [comment]
> Unfortunately this is impossible without hooking into DWM, which is not something I'm planning to do (it's just too many risks for little yields). @xmine64 what are your opinions?

SetWindowCompositionAttribute?

**Comment by dongle-the-gadget** [comment]
> SetWindowCompositionAttribute?

This is a different implementation (composition attribute vs backdrop attribute), and has a variety of bugs as an internal API.

**Comment by manmathew** [comment]
I'm guessing the answer will stay the same, but I noticed that when dragging a window with touchscreen, a layer of acrylic is added behind the window. You can actually see that it's behind the entire window area if you drag Explorer for example, and it essentially darkens the background while keeping the acrylic effect (albeit stronger with both layers). I would also like to note that this is default behavior of Windows 11 (at least I think, it's possible it isn't originally acrylic and MfE is making it so). So my question would be if it's possible to add a layer behind windows that essentially does the exact same thing, but all the time. Asking if it's possible without hooking into DWM since that seems to be the issue in this case.

**Comment by dongle-the-gadget** [comment]
That's because for the case with Mica, it's actually a blurred and tinted wallpaper. It's still controlled by DWM regardless, though.
